### ISSUE TITLE
Int16 raster support

### ISSUE THREAD

**Issue by knutole** [mapic/mapic.js#29]
Both single and in cube.

- [x] Styler needs to detect `int16` for range
- [x] Styler must work with `int16`
- [ ] Styler must work with cube with `int16` 
- [x] click on layer for query (on cube)
- [x] click on layer for single value?
- [x] legend for int16 cube
- [ ] transect

**Comment by knutole** [comment]
## Raster deformation
- må laste opp egen mvel
- ikke cube layer, men egen type (`defo`)
- denne typen har et hovedlag (mvel), og "datalag", som er de forskjellige dagene. Disse lagene brukes kun til å trekke ut verdier for tidsserie.
- eget script i `sdk`
- en undertype av `model.layer.raster.js`, eg. `model.layer.raster.defo.js` 


## Fix bugs in snow
- put `sync-ftp.api.sh` in cronjob on `px`
- fix 2017 bug
- fix minor bugs

**Comment by knutole** [comment]
### TODO
- [ ] set min/max of legends
- [ ] create legend automatically
- [ ] GUI for creating deformation raster datasets (with mvel / raw query sets)
